### ISSUE TITLE
图片保存功能

### ISSUE THREAD

**Issue by JRY-Zheng** [soyaine/jocker-chrome-extension#13]
目前Jocker仅能将文字部分保存为csv，无法保存图片。我看了下代码，应该是规划过图片保存功能，但是又注释掉了。把注释代码恢复回来，应该只能保存图片的链接。以下是我的猜想：

_在浏览器端仅能一次保存一张图片，如果图片数量较多，调起很多下载进程，不仅体验不好，还可能会把浏览器搞挂。常规操作应该是将所有图片压缩打包后再下载，但是这个在浏览器端无法实现，必须要把图片保存到服务器，由服务器压缩后提供下载。这不仅要求有服务器，还涉及隐私等问题，比较麻烦。_

请问你是不是因为这个原因没有实现保存图片的功能？如果不是的话，还请说明一下原因，或许我能帮帮忙。

**Comment by soyaine** [comment]
主要原因是，我此前有看到一种备份图片的方法，是类似保存整个HTML到本地，这时会自动创建一个文件夹存储所有图片到本地，且未来依然可以在本地浏览HTML。

这意味着不需要开发就可以解决，但由于没有经过操作验证，不确定是否真的可行有效，我没有写到说明里。

**Comment by JRY-Zheng** [comment]
这么操作是可行的，我就是这么操作的。但是这样下载下来的图片全都在一个文件夹里，只有打开html时才知道哪个图片在哪条动态里，而且图片的名称也是乱的。当然确实也能解决问题。

**Comment by soyaine** [comment]
@JRY-Zheng 那想再多问一个问题，你对于图片备份的需求是希望和动态内容或标签绑定吗？

**Comment by JRY-Zheng** [comment]
我觉得这样会更好一点~
